version: '3.8'

services:
  kafka:
    container_name: ecmckafka-db
    image: bashj79/kafka-kraft
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/opt/kafka/kafka-logs
  mongodb:
    container_name: ecmcfilter-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  mongodb-invoice:
    container_name: ecmcinvoice-db
    image: mongo
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data_invoice:/data/db
  mongodb-basket:
    container_name: ecmcbasket-db
    image: mongo
    ports:
      - "27019:27019"
    volumes:
      - mongodb_data_basket:/data/db

volumes:
  kafka_data:
  mongodb_data:
  mongodb_data_invoice:
  mongodb_data_basket: