spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        default-label: master
        git:
          uri: https://github.com/batuyirtici/E-Commerce-Microservice-Config-Server
server:
  port: 8888